# Generated by Django 5.0.2 on 2024-03-31 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="blogs"),
        ),
    ]
