# Generated by Django 5.0.2 on 2024-04-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Posts", "0002_alter_post_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("news_status", models.BooleanField(default=False)),
            ],
        ),
    ]
