# Generated by Django 5.0.2 on 2024-04-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Posts", "0004_contact_alter_newsletter_news_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                default="category/default.jpg", upload_to="categories"
            ),
        ),
    ]
