# Generated by Django 5.0.2 on 2024-04-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Posts", "0005_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="text",
            field=models.CharField(default=None, max_length=350),
        ),
    ]
