# Generated by Django 4.2 on 2024-06-06 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0007_remove_category_image_remove_category_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_date']},
        ),
    ]
